workflows:
    react-native:
        name: ImadApp
        environment:
            vars:
                XCODE_WORKSPACE: "ImadApp"
                XCODE_SCHEME: "ImadApp"
            node: latest
        scripts:
          - name: Install dependencies
            script: |
              npm install
          - name: Run tests
            script: |
              echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          - name: Build Android
            script: |
              cd android && ./gradlew assembleDebug
          - name: Build iOS
            script: |
              cd ios && pod install &&
              xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - android/app/build/outputs/**/**/*.apk
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
